In [1]:
import tensorflow as tf2

In [2]:
tf2.__version__

'2.1.0'

In [3]:
# Adaptação para utilizar a sintaxe do TensorFlor 1.x no TensorFlow 2.x
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_error

<br/><br/>
## 1. Sintaxe Básica

### 1.1 Constantes

In [5]:
# Definir constantes
const1 = tf.constant(2)
const2 = tf.constant(3)
print(const1)

Tensor("Const:0", shape=(), dtype=int32)


In [6]:
# Visualizar tipo da variável
type(const1)

tensorflow.python.framework.ops.Tensor

In [7]:
soma = const1 + const2
type(soma)

tensorflow.python.framework.ops.Tensor

In [8]:
# Para executar o fluxo dos tensores que compõem o grafo, é necessário sempre iniciar uma sessão
with tf.Session() as sess:
    s = sess.run(soma)
    print('Const1 =', const1.eval())
    print('Const2 =', const2.eval())
    print('Soma =', s)

Const1 = 2
Const2 = 3
Soma = 5


In [9]:
string1 = tf.constant('texto 1 ')
string2 = tf.constant('texto 2')

In [10]:
concat = string1 + string2

In [11]:
with tf.Session() as sess:
    s = sess.run(concat)
    print(s)

b'texto 1 texto 2'


<br/> 
### 1.2 Variáveis

In [12]:
# Definir variaveis
var1 = tf.Variable(5, name='variable1')
print(var1)

<tf.Variable 'variable1:0' shape=() dtype=int32_ref>


In [13]:
soma = tf.Variable(var1 + 5, name='soma5')
print(soma)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
<tf.Variable 'soma5:0' shape=() dtype=int32_ref>


In [14]:
# É necessário inicializar as variáveis antes de iniciar a sessão
var_init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(var_init)
    s = sess.run(soma)
    
    print('Variable1 =', var1.eval())
    print('Soma 5 =', s)

Variable1 = 5
Soma 5 = 10


In [15]:
vetor1 = tf.constant([3,5,7], name='vetor1')

In [16]:
soma_vetor = tf.Variable(vetor1 + 5, name='somaVetor')

In [17]:
var_init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(var_init)
    s = sess.run(soma_vetor)
    
    print('Vetor  =', vetor1.eval())
    print('Soma 5 =', s)

Vetor  = [3 5 7]
Soma 5 = [ 8 10 12]


<br/> 
### 1.3 Adição de Vetores/Matrizes

In [18]:
vetorA = tf.constant([9, 8, 7], name='vetorA')
vetorB = tf.constant([1, 2, 3], name='vetorB')

In [19]:
soma_vetor = vetorA + vetorB

In [20]:
with tf.Session() as sess:
    s = sess.run(soma_vetor)
    print(s)

[10 10 10]


In [21]:
matrizA = tf.constant([[1,2,3], [4,5,6]], name='matrizA')
matrizB = tf.constant([[1,2,3], [4,5,6]], name='matrizB')

In [22]:
soma_matriz = tf.add(matrizA, matrizB)

In [23]:
with tf.Session() as sess:
    s = sess.run(soma_matriz)
    print(s)

[[ 2  4  6]
 [ 8 10 12]]


In [24]:
matrizB2 = tf.constant([[1], [10]])
soma_matriz2 = tf.add(matrizA, matrizB2)

In [25]:
with tf.Session() as sess:
    s = sess.run(soma_matriz2)
    print(sess.run(matrizA), '\n')
    print(sess.run(matrizB2), '\n')
    print(s)

[[1 2 3]
 [4 5 6]] 

[[ 1]
 [10]] 

[[ 2  3  4]
 [14 15 16]]


<br/> 
### 1.4 Multiplicação (Dot Product)

In [26]:
vetorA = tf.constant([[1,2], [3,4]])
vetorB = tf.constant([[-1, 3], [4, 2]])

In [27]:
dot_product = tf.multiply(matrizA, matrizB)

In [28]:
with tf.Session() as sess:
    s = sess.run(dot_product)
    print(sess.run(vetorA), '\n')
    print(sess.run(vetorB), '\n')
    print(s, '\n')
    print(sess.run(tf.reduce_sum(dot_product))) # soma de todos os elementos da matriz resultante

[[1 2]
 [3 4]] 

[[-1  3]
 [ 4  2]] 

[[ 1  4  9]
 [16 25 36]] 

91


### 1.5 Multiplicação de Matrizes

In [29]:
matrizA = tf.constant([[1,2], [3,4]])
matrizB = tf.constant([[-1, 3], [4, 2]])

In [30]:
mult_matriz = tf.matmul(matrizA, matrizB)

In [31]:
with tf.Session() as sess:
    s = sess.run(mult_matriz)
    print(sess.run(matrizA), '\n')
    print(sess.run(matrizB), '\n')
    print(s)

[[1 2]
 [3 4]] 

[[-1  3]
 [ 4  2]] 

[[ 7  7]
 [13 17]]


<br/> 
### 1.6 Placeholders

In [32]:
# Variável que não contém dados inicialmente. É inicializado somente com o tipo de dado esperado
pholder = tf.placeholder('float', shape=None) # shape=None, placeholder admite qualquer dimensão
pholder2 = tf.placeholder('float', shape=(None, 3))

In [33]:
operacao = pholder + 2
operacao2 = pholder2 * 5

In [34]:
# feed_dict alimenta o placeholder com valores
with tf.Session() as sess:
    resultado1 = sess.run(operacao, feed_dict={pholder : [[1, 2], [3, 4]]})
    resultado2 = sess.run(operacao2, feed_dict={pholder2 : [[1, 2, 3], [4, 5, 6]]})
    print(resultado1, '\n')
    print(resultado2)

[[3. 4.]
 [5. 6.]] 

[[ 5. 10. 15.]
 [20. 25. 30.]]


<br/> 
### 1.7 Grafos e TensorBoard

In [35]:
# Reseta os grafos de outras sessões
tf.reset_default_graph()

In [36]:
a = tf.add(2, 2, name='add')
b = tf.multiply(a, 3, name='mult1')
c = tf.multiply(b, a, name='mult2')

In [37]:
# Definir escopos para tornar o grafo mais organizado
with tf.name_scope('Operacoes'):
    with tf.name_scope('Escopo_A'):
        a = tf.add(2, 2, name='add')
    with tf.name_scope('Escopo_B'):
        b = tf.multiply(a, 3, name='mult1')
        c = tf.multiply(b, a, name='mult2')

In [38]:
with tf.Session() as sess:
    print(sess.run(c))
    
    # Cria o grafo referente a operação. Grafo pode ser visualizado utilizando o Tensor Board
    writer = tf.summary.FileWriter('output', sess.graph)
    writer.close()

48


In [39]:
# Para visualizar o grafo:
# Abrir terminal
# digitar: tensorboard --logdir=[diretorio_do_arquivo]
# abrir o endereço http gerado no navegador

In [40]:
tf.get_default_graph()

In [41]:
# Cria um novo grafo
# É possível fazer com que cada máquina fique responsável por processar um determinado grafo
grafo2 = tf.Graph()

In [42]:
with grafo2.as_default():
    print(grafo2 is tf.get_default_graph())

True
